-- Databricks notebook source
-- MAGIC %md
-- MAGIC # Delta End-to-End — Topics 3, 4 & 5 Combined
-- MAGIC
-- MAGIC **Pure SQL. No Python.**
-- MAGIC
-- MAGIC This notebook merges three lessons into one continuous story, using **one catalog,
-- MAGIC one schema and one table** throughout:
-- MAGIC
-- MAGIC - **Topic 3** — creating and managing Delta tables
-- MAGIC - **Topic 4** — time travel and querying historical versions
-- MAGIC - **Topic 5** — restore and rollback strategies
-- MAGIC
-- MAGIC The standalone notebooks in `03_delta_tables/`, `04_time_travel/` and
-- MAGIC `05_restore_rollback/` are unchanged — use those to teach a single topic. Use
-- MAGIC **this** one to present all three in sequence.
-- MAGIC
-- MAGIC ## What is different here
-- MAGIC The separate notebooks each build their own catalog, schema and table, and each
-- MAGIC re-explains history and `RESTORE`. That repetition is right when they stand alone
-- MAGIC and wrong when they run together. Here:
-- MAGIC
-- MAGIC - **One table, `orders`**, carried through every section — so the history you
-- MAGIC   inspect in Part 3 is the history *you just created* in Part 2
-- MAGIC - **Each command appears once**, at the point in the story where it belongs
-- MAGIC - The order is deliberate: **schema changes come after the recovery section**, so
-- MAGIC   restoring to an early version never conflicts with a later column
-- MAGIC
-- MAGIC ## The arc
-- MAGIC | Part | Question it answers |
-- MAGIC |---|---|
-- MAGIC | 1 | How do I create a Delta table? |
-- MAGIC | 2 | How do I change the data in it? |
-- MAGIC | 3 | What happened to this table, and what did it look like before? |
-- MAGIC | 4 | Something went wrong — how do I undo it? |
-- MAGIC | 5 | The business changed — how do I evolve the table? |
-- MAGIC | 6 | How do I keep it fast, cheap and recoverable? |
-- MAGIC
-- MAGIC Uses its own catalog, **`demo_delta_e2e`**, dropped first so everything is built
-- MAGIC live. It does not touch the catalogs used by the standalone notebooks.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC # Part 1 — Creating a Delta table
-- MAGIC
-- MAGIC ## Why Delta at all?
-- MAGIC Every table in Databricks is a **Delta table** by default. Delta is what makes a
-- MAGIC folder of files in cloud storage behave like a real database table:
-- MAGIC
-- MAGIC | Without Delta | With Delta |
-- MAGIC |---|---|
-- MAGIC | To change one row, rewrite everything | `UPDATE` / `DELETE` / `MERGE` |
-- MAGIC | A failed job leaves half-written data | Writes are all-or-nothing |
-- MAGIC | Overwrite a file and yesterday is gone | Every version is kept |
-- MAGIC | Wrong-shaped data lands silently | Schema is enforced |
-- MAGIC
-- MAGIC Those four properties are what the rest of this notebook is built on.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 1 — Clean slate
-- MAGIC
-- MAGIC `CASCADE` removes everything inside; `IF EXISTS` stops it erroring on a first run.
-- MAGIC Together they make the notebook repeatable — present it twice, get identical
-- MAGIC results.

-- COMMAND ----------

DROP CATALOG IF EXISTS demo_delta_e2e CASCADE;

-- COMMAND ----------

CREATE CATALOG IF NOT EXISTS demo_delta_e2e
  COMMENT 'Combined Delta lifecycle lesson (topics 3-5). Safe to drop and recreate.';

CREATE SCHEMA IF NOT EXISTS demo_delta_e2e.sales
  COMMENT 'Single schema reused across the whole lesson.';

USE CATALOG demo_delta_e2e;
USE SCHEMA sales;

SELECT current_catalog() AS catalog, current_schema() AS schema;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 2 — Create the one table we will use throughout
-- MAGIC
-- MAGIC Three things in this definition are worth pausing on:
-- MAGIC
-- MAGIC - **`GENERATED BY DEFAULT AS IDENTITY`** — Delta assigns the id when you do not
-- MAGIC   supply one. No sequence table, no two jobs picking the same number.
-- MAGIC
-- MAGIC   **Why `BY DEFAULT` and not `ALWAYS`?** This is a real trap. `GENERATED ALWAYS`
-- MAGIC   *forbids* supplying the column explicitly — which means you cannot insert rows
-- MAGIC   back from a backup or clone, because that would require writing the original
-- MAGIC   ids. Any recovery that re-inserts rows fails with
-- MAGIC   `DELTA_IDENTITY_COLUMNS_EXPLICIT_INSERT_NOT_SUPPORTED`.
-- MAGIC
-- MAGIC   `BY DEFAULT` gives you both: automatic ids for normal inserts, and the ability
-- MAGIC   to write explicit ids when restoring. **If a table needs to be recoverable, use
-- MAGIC   `BY DEFAULT`.** We rely on this in Part 4.
-- MAGIC - **`NOT NULL`** — a real constraint. A write that breaks it is *rejected*, not
-- MAGIC   quietly stored.
-- MAGIC - **`delta.enableChangeDataFeed = true`** — records the before/after image of every
-- MAGIC   changed row. We use it in Part 3.
-- MAGIC
-- MAGIC **Enable Change Data Feed at creation time.** It only captures changes made after
-- MAGIC it is switched on, so turning it on later leaves a gap you cannot backfill.

-- COMMAND ----------

CREATE TABLE orders (
  order_id   BIGINT GENERATED BY DEFAULT AS IDENTITY COMMENT 'Auto-assigned unique order id',
  customer   STRING NOT NULL                     COMMENT 'Customer name - required',
  region     STRING                              COMMENT 'Sales region',
  product    STRING                              COMMENT 'Product ordered',
  quantity   INT                                 COMMENT 'Units ordered',
  unit_price DECIMAL(10,2)                       COMMENT 'Price per unit at time of sale',
  order_date DATE                                COMMENT 'Date the order was placed',
  status     STRING                              COMMENT 'placed, shipped, delivered or cancelled'
)
COMMENT 'Customer orders. Single table used across the whole Delta lifecycle lesson.'
TBLPROPERTIES (delta.enableChangeDataFeed = true);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 3 — Load the data
-- MAGIC
-- MAGIC We omit `order_id` because Delta generates it. This `INSERT` is a **transaction**:
-- MAGIC all six rows land, or none do. Had the cluster died mid-write, a reader would see
-- MAGIC the table exactly as it was before — never a partial load.
-- MAGIC
-- MAGIC **This becomes version 1, and it is our known-good state for the rest of the
-- MAGIC notebook.** Remember these totals.

-- COMMAND ----------

INSERT INTO orders (customer, region, product, quantity, unit_price, order_date, status) VALUES
  ('Aarav Sharma',   'South', 'Laptop',   1, 1200.00, DATE'2025-01-10', 'delivered'),
  ('Priya Nair',     'South', 'Monitor',  2,  300.00, DATE'2025-01-12', 'shipped'),
  ('Rohan Iyer',     'West',  'Keyboard', 3,   80.00, DATE'2025-01-15', 'placed'),
  ('Meera Krishnan', 'West',  'Laptop',   1, 1200.00, DATE'2025-02-02', 'delivered'),
  ('Vikram Rao',     'North', 'Mouse',    5,   25.00, DATE'2025-02-08', 'placed'),
  ('Nisha Menon',    'North', 'Monitor',  1,  300.00, DATE'2025-02-14', 'cancelled');

-- COMMAND ----------

SELECT region, count(*) AS orders, sum(quantity * unit_price) AS revenue
FROM orders GROUP BY region ORDER BY region;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 4 — What is this table physically?
-- MAGIC
-- MAGIC The format is `delta`. **Watch `numFiles`** — Delta writes new files rather than
-- MAGIC editing existing ones, so this number grows with every change. That is exactly the
-- MAGIC problem `OPTIMIZE` solves in Part 6.

-- COMMAND ----------

DESCRIBE DETAIL orders;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC # Part 2 — Changing data
-- MAGIC
-- MAGIC Each statement below creates a new version. By the end of this part the table has
-- MAGIC a real history — which is what Part 3 inspects.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 5 — `UPDATE`: change rows in place
-- MAGIC
-- MAGIC **This is the headline feature.** In a plain data lake you could not do this at
-- MAGIC all — you rewrote the whole dataset to change one value.

-- COMMAND ----------

UPDATE orders
SET status = 'shipped'
WHERE status = 'placed' AND order_date < DATE'2025-02-01';

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 6 — `DELETE`: remove rows
-- MAGIC
-- MAGIC Beyond convenience, this is what makes **GDPR erasure** practical. "Delete
-- MAGIC everything about this person" used to be a project; here it is one statement, and
-- MAGIC it is recorded in the history so you can *prove* you did it.

-- COMMAND ----------

DELETE FROM orders WHERE status = 'cancelled';

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 7 — `MERGE`: the upsert
-- MAGIC
-- MAGIC The most useful Delta statement. It solves the everyday problem:
-- MAGIC
-- MAGIC > *"Here is today's file from the source system. Some rows update orders we already
-- MAGIC > have; some are new. Sort it out."*
-- MAGIC
-- MAGIC Written by hand that is a delete-then-insert inside a transaction, and easy to get
-- MAGIC subtly wrong. `MERGE` does it atomically: **matched** rows update, **unmatched**
-- MAGIC rows insert.

-- COMMAND ----------

CREATE OR REPLACE TEMP VIEW incoming AS
SELECT * FROM VALUES
  (1,  'Aarav Sharma', 'South', 'Laptop', 1, 1200.00, DATE'2025-01-10', 'returned'),
  (99, 'Kavya Reddy',  'West',  'Tablet', 1,  450.00, DATE'2025-03-01', 'placed')
AS t(order_id, customer, region, product, quantity, unit_price, order_date, status);

-- COMMAND ----------

MERGE INTO orders AS target
USING incoming AS source
  ON target.order_id = source.order_id
WHEN MATCHED THEN
  UPDATE SET target.status = source.status
WHEN NOT MATCHED THEN
  INSERT (customer, region, product, quantity, unit_price, order_date, status)
  VALUES (source.customer, source.region, source.product, source.quantity,
          source.unit_price, source.order_date, source.status);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC Order 1 now reads `returned`, and Kavya Reddy's tablet order has appeared. **All of
-- MAGIC it, or none of it** — a `MERGE` cannot half-apply.

-- COMMAND ----------

SELECT order_id, customer, region, product, status FROM orders ORDER BY order_id;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC # Part 3 — History and time travel
-- MAGIC
-- MAGIC We have made four changes. Delta recorded every one, without being asked.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 8 — Reading the history
-- MAGIC
-- MAGIC | Column | Tells you |
-- MAGIC |---|---|
-- MAGIC | `version` | The number you pass to `VERSION AS OF` |
-- MAGIC | `timestamp` | When it happened |
-- MAGIC | `userName` | **Who** made the change |
-- MAGIC | `operation` | `WRITE`, `UPDATE`, `DELETE`, `MERGE`… |
-- MAGIC | `operationMetrics` | How many rows were added, changed or removed |
-- MAGIC
-- MAGIC Together: *who changed what, when, and how much* — with no auditing framework, no
-- MAGIC triggers, no extra tables. It is simply on.

-- COMMAND ----------

DESCRIBE HISTORY orders;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### A readable audit log
-- MAGIC History is queryable, so we can select just the useful parts — the sort of view you
-- MAGIC would hand an auditor. `numOutputRows` shows the *size* of each change, so an
-- MAGIC unexpectedly large one stands out immediately.

-- COMMAND ----------

SELECT
  version,
  timestamp,
  userName                           AS changed_by,
  operation,
  operationMetrics['numOutputRows']  AS rows_written,
  operationMetrics['numDeletedRows'] AS rows_deleted,
  operationMetrics['numUpdatedRows'] AS rows_updated
FROM (DESCRIBE HISTORY orders)
ORDER BY version;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 9 — Querying an old version
-- MAGIC
-- MAGIC `VERSION AS OF 1` is the original load — before the update, delete and merge. The
-- MAGIC cancelled order is back and order 1 is `delivered` again.
-- MAGIC
-- MAGIC Reading the past costs nothing extra: those files were never deleted.

-- COMMAND ----------

SELECT order_id, customer, region, status FROM orders VERSION AS OF 1 ORDER BY order_id;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### The `@v` shorthand
-- MAGIC `orders@v1` means the same thing, and works anywhere a table name works — which is
-- MAGIC what makes the next step possible.
-- MAGIC
-- MAGIC ### On `TIMESTAMP AS OF`
-- MAGIC You can also travel by time:
-- MAGIC
-- MAGIC ```sql
-- MAGIC SELECT * FROM orders TIMESTAMP AS OF '2025-03-01';
-- MAGIC ```
-- MAGIC
-- MAGIC **We do not run it here, and the reason is instructive.** Delta rejects a timestamp
-- MAGIC *before the first commit* (`DELTA_TIMESTAMP_BEFORE_FIRST_COMMIT`) and *after the
-- MAGIC latest commit* (`DELTA_TIMESTAMP_GREATER_THAN_COMMIT`). This table was created
-- MAGIC seconds ago, so every fixed date fails one test or the other. Variables and
-- MAGIC subqueries do not help — the clause requires a constant.
-- MAGIC
-- MAGIC > **The rule this leads to: use timestamps to explore, version numbers to
-- MAGIC > reproduce.** A version number means exactly one state forever. Anything that must
-- MAGIC > be repeatable — a regulatory report, a model's training set — should pin a
-- MAGIC > **version**.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 10 — Comparing two points in time
-- MAGIC
-- MAGIC Because any version behaves like an ordinary table, **you can join the past to the
-- MAGIC present**. "What changed since the initial load?" becomes one query.
-- MAGIC
-- MAGIC This is the pattern that settles most "the numbers don't match" disputes.

-- COMMAND ----------

SELECT
  coalesce(old.order_id, new.order_id) AS order_id,
  coalesce(old.customer, new.customer) AS customer,
  old.status AS status_at_v1,
  new.status AS status_now,
  CASE
    WHEN old.order_id IS NULL                     THEN 'ADDED since v1'
    WHEN new.order_id IS NULL                     THEN 'REMOVED since v1'
    WHEN old.status IS DISTINCT FROM new.status   THEN 'STATUS CHANGED'
    ELSE 'unchanged'
  END AS change_type
FROM      orders@v1 AS old
FULL JOIN orders    AS new ON old.order_id = new.order_id
ORDER BY order_id;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 11 — Change Data Feed: the row-by-row story
-- MAGIC
-- MAGIC Comparing versions gives the **net** difference. Change Data Feed gives the
-- MAGIC **individual** changes, including before/after images and changes that later
-- MAGIC cancelled out and would be invisible in a diff.
-- MAGIC
-- MAGIC | `_change_type` | Meaning |
-- MAGIC |---|---|
-- MAGIC | `insert` / `delete` | Row added or removed |
-- MAGIC | `update_preimage` | The row **before** an update |
-- MAGIC | `update_postimage` | The row **after** an update |
-- MAGIC
-- MAGIC **Why it matters:** it lets you feed downstream systems only what changed, instead
-- MAGIC of reprocessing everything nightly — and it is the cleanest answer to *"what was
-- MAGIC the prior value of this field?"*

-- COMMAND ----------

SELECT _change_type, _commit_version, order_id, customer, status
FROM table_changes('orders', 1)
ORDER BY _commit_version, order_id, _change_type;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### Before and after on one line
-- MAGIC Pairing the images turns the feed into a plain-English change log.

-- COMMAND ----------

SELECT
  before._commit_version AS version,
  before.order_id,
  before.customer,
  before.status AS status_before,
  after.status  AS status_after
FROM table_changes('orders', 1) AS before
JOIN table_changes('orders', 1) AS after
  ON before.order_id = after.order_id
 AND before._commit_version = after._commit_version
WHERE before._change_type = 'update_preimage'
  AND after._change_type  = 'update_postimage'
ORDER BY version, order_id;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC # Part 4 — Recovery: when something goes wrong
-- MAGIC
-- MAGIC Time travel *reads* the past. Recovery *returns* to it. There are five strategies,
-- MAGIC and `RESTORE` is only one — often the wrong one.
-- MAGIC
-- MAGIC ## The principle
-- MAGIC **Match the size of the fix to the size of the problem.** Restoring an entire table
-- MAGIC because forty rows are wrong also discards every *correct* change made since —
-- MAGIC including other people's work. That is a second incident caused by the response to
-- MAGIC the first.
-- MAGIC
-- MAGIC | Situation | Strategy |
-- MAGIC |---|---|
-- MAGIC | Whole table wrong, nothing good since | Full `RESTORE` |
-- MAGIC | Some rows wrong, good work must survive | Surgical `MERGE` |
-- MAGIC | Table was dropped | `UNDROP TABLE` |
-- MAGIC | About to do something risky | Clone checkpoint |
-- MAGIC | Rebuilding a live table | Blue/green swap |

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 12 — Strategy A: full `RESTORE`
-- MAGIC
-- MAGIC The classic disaster: a job ran without its `WHERE` clause.

-- COMMAND ----------

-- The 2am mistake: intended for one region, applied to everything.
UPDATE orders SET unit_price = 0.00;

SELECT region, sum(quantity * unit_price) AS revenue FROM orders GROUP BY region ORDER BY region;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC Every total is zero. Version 1 was our known-good state, so `RESTORE` returns the
-- MAGIC table to it — in seconds regardless of size, because no data moves. The log simply
-- MAGIC points at the earlier files again.
-- MAGIC
-- MAGIC **`RESTORE` is itself a new version**, so the undo is auditable and reversible.

-- COMMAND ----------

RESTORE TABLE orders TO VERSION AS OF 1;

SELECT region, count(*) AS orders, sum(quantity * unit_price) AS revenue
FROM orders GROUP BY region ORDER BY region;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### The catch nobody mentions
-- MAGIC `RESTORE` is **all or nothing for the whole table**. Had a colleague inserted ten
-- MAGIC legitimate orders after the bad update, restoring would silently discard those too.
-- MAGIC
-- MAGIC That is why the next strategy exists.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 13 — Strategy B: surgical repair
-- MAGIC
-- MAGIC **Use when** only some rows are wrong, or good changes have happened since and must
-- MAGIC be kept.
-- MAGIC
-- MAGIC The insight: **an old version is just a table**, so you can `MERGE` from the past
-- MAGIC into the present and repair only the rows you name.
-- MAGIC
-- MAGIC Let us build exactly that mixed situation.

-- COMMAND ----------

-- Damage: a bad job corrupted the South region only.
UPDATE orders SET unit_price = 1.00 WHERE region = 'South';

-- Meanwhile legitimate business continued.
INSERT INTO orders (customer, region, product, quantity, unit_price, order_date, status)
VALUES ('Arjun Pillai', 'West', 'Headset', 2, 150.00, DATE'2025-03-05', 'placed');

-- COMMAND ----------

-- MAGIC %md
-- MAGIC South is corrupted, but Arjun's order is genuine. A full `RESTORE` would fix South
-- MAGIC **and delete Arjun's order.** Unacceptable.

-- COMMAND ----------

SELECT order_id, customer, region, unit_price FROM orders ORDER BY order_id;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### The surgical fix
-- MAGIC Merge back **only the South rows** from the last good version. The `WHERE` in the
-- MAGIC source is what scopes the blast radius — the difference between a targeted repair
-- MAGIC and a blunt rollback.

-- COMMAND ----------

MERGE INTO orders AS target
USING (SELECT * FROM orders VERSION AS OF 1 WHERE region = 'South') AS good
  ON target.order_id = good.order_id
WHEN MATCHED THEN UPDATE SET target.unit_price = good.unit_price;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC South is repaired **and** Arjun's order survives. On any table with more than one
-- MAGIC writer, this is almost always the right choice.

-- COMMAND ----------

SELECT order_id, customer, region, unit_price FROM orders ORDER BY order_id;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 14 — Strategy C: `UNDROP` a deleted table
-- MAGIC
-- MAGIC `RESTORE` cannot help when the table itself is gone — there is nothing to restore
-- MAGIC *into*. Unity Catalog keeps a dropped **managed** table recoverable for **7 days**,
-- MAGIC with data and history intact.
-- MAGIC
-- MAGIC "Someone dropped the production table" used to mean restoring from backup. Now it
-- MAGIC is one statement.

-- COMMAND ----------

CREATE OR REPLACE TABLE order_audit AS
SELECT order_id, customer, unit_price FROM orders;

SELECT count(*) AS rows_before_drop FROM order_audit;

-- COMMAND ----------

DROP TABLE order_audit;

-- COMMAND ----------

UNDROP TABLE order_audit;

SELECT count(*) AS rows_after_undrop FROM order_audit;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC > **Two limits.** The window is **7 days** — after that it is genuinely gone. And
-- MAGIC > `UNDROP` covers managed tables; an external table's files were never deleted, so
-- MAGIC > you re-register it instead.
-- MAGIC >
-- MAGIC > Dropping a **catalog or schema** with `CASCADE` is a far bigger event than
-- MAGIC > dropping one table. Treat it as change-controlled, not something typed casually.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 15 — Strategy D: clones as restore points
-- MAGIC
-- MAGIC | | `SHALLOW CLONE` | `DEEP CLONE` |
-- MAGIC |---|---|---|
-- MAGIC | Copies data files | **No** — points at the originals | **Yes** — a real copy |
-- MAGIC | Speed | Instant, even on huge tables | Proportional to size |
-- MAGIC | Extra storage | Almost none | A full second copy |
-- MAGIC | Survives `VACUUM` of the source | **No** — it breaks | **Yes** — independent |
-- MAGIC | Good for | Short-lived checkpoints, test copies | Real backups |
-- MAGIC
-- MAGIC **The trap: a shallow clone looks like a backup and is not one.** It shares the
-- MAGIC source's files, so vacuuming the source can leave it unreadable. Shallow for "I'll
-- MAGIC be done in an hour"; deep for anything you actually rely on.

-- COMMAND ----------

-- Instant checkpoint before a risky change. Near-zero storage.
CREATE OR REPLACE TABLE orders_checkpoint SHALLOW CLONE orders;

-- A durable backup, independent of the source's files and VACUUM schedule.
CREATE OR REPLACE TABLE orders_backup DEEP CLONE orders;

SELECT (SELECT count(*) FROM orders_checkpoint) AS in_checkpoint,
       (SELECT count(*) FROM orders_backup)     AS in_backup;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### Recovering from a checkpoint
-- MAGIC With a checkpoint in hand, recovery does not depend on reading history at all — you
-- MAGIC merge from a table you can see and query.

-- COMMAND ----------

DELETE FROM orders WHERE region = 'North';

MERGE INTO orders AS target
USING orders_checkpoint AS backup
  ON target.order_id = backup.order_id
WHEN NOT MATCHED THEN INSERT *;

SELECT count(*) AS rows_after_recovery FROM orders;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 16 — Rehearse the rollback before running it
-- MAGIC
-- MAGIC The most valuable habit here, and the most often skipped. **Never test a recovery
-- MAGIC on production.** Clone, rehearse the whole incident *and* the recovery on the
-- MAGIC clone, check the numbers, *then* do it for real. A clone is instant and nearly
-- MAGIC free — there is no excuse.
-- MAGIC
-- MAGIC > **A gotcha worth knowing: a clone starts its own history at version 0.** The
-- MAGIC > source table's versions are **not** carried over, so
-- MAGIC > `RESTORE ... TO VERSION AS OF 1` on a fresh clone fails with
-- MAGIC > `DELTA_CANNOT_RESTORE_TABLE_VERSION - Available versions: [0, 0]`.
-- MAGIC >
-- MAGIC > That is not a limitation so much as a reminder of what a clone is: a new table
-- MAGIC > that happens to start with the same data. To rehearse, make the change on the
-- MAGIC > clone first — then version 0 is your known-good point.

-- COMMAND ----------

-- 1. Take the rehearsal copy. Its history starts at version 0.
CREATE OR REPLACE TABLE orders_rehearsal SHALLOW CLONE orders;

-- COMMAND ----------

-- 2. Rehearse the incident on the copy, never on production.
DELETE FROM orders_rehearsal WHERE region = 'West';

SELECT 'after simulated incident' AS which, count(*) AS rows FROM orders_rehearsal;

-- COMMAND ----------

-- 3. Rehearse the recovery. Version 0 is the clone's known-good state.
RESTORE TABLE orders_rehearsal TO VERSION AS OF 0;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### 4. Confirm the rehearsal worked — and that production was never touched
-- MAGIC Now you know the command does what you expect, and you learned it at zero risk.

-- COMMAND ----------

SELECT 'rehearsal after restore' AS which, count(*) AS rows FROM orders_rehearsal
UNION ALL
SELECT 'production (untouched)',            count(*)         FROM orders;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC # Part 5 — Evolving the table
-- MAGIC
-- MAGIC Deliberately placed **after** recovery: adding a column changes the schema, and
-- MAGIC restoring to a version that predates it would remove the column again. Teaching the
-- MAGIC order this way avoids that confusion entirely.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 17 — Schema evolution
-- MAGIC
-- MAGIC Business needs change. Delta adds a column **without rebuilding the table** —
-- MAGIC existing rows simply show `NULL`.
-- MAGIC
-- MAGIC The key word is *deliberately*. Delta's **schema enforcement** rejects unexpected
-- MAGIC columns by default; changing shape must be stated explicitly. Locked down by
-- MAGIC default, changeable on purpose — that is what prevents silent corruption.

-- COMMAND ----------

ALTER TABLE orders ADD COLUMN discount_pct INT COMMENT 'Discount applied, as a percentage';

UPDATE orders SET discount_pct = 10 WHERE quantity >= 3;
UPDATE orders SET discount_pct = 0  WHERE discount_pct IS NULL;

SELECT order_id, customer, quantity, discount_pct FROM orders ORDER BY order_id;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 18 — Constraints: refuse bad data at the door
-- MAGIC
-- MAGIC A `CHECK` constraint is a rule the table enforces on every future write.
-- MAGIC
-- MAGIC **Why in the table rather than in the pipeline?** Because tables usually have more
-- MAGIC than one writer. A rule in one job protects one path; a rule on the table protects
-- MAGIC every path forever — including the ad-hoc `INSERT` someone runs at 6pm.
-- MAGIC
-- MAGIC Adding it also validates existing rows, so it fails immediately if the data already
-- MAGIC violates the rule.

-- COMMAND ----------

ALTER TABLE orders ADD CONSTRAINT positive_quantity CHECK (quantity > 0);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC Any future insert with `quantity <= 0` is now rejected outright.
-- MAGIC
-- MAGIC *(We do not demonstrate the rejection, because a deliberately failing cell would
-- MAGIC stop the notebook. Mention it verbally, or try it in a scratch cell.)*

-- COMMAND ----------

-- MAGIC %md
-- MAGIC # Part 6 — Keeping it fast, cheap and recoverable

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 19 — `OPTIMIZE`: fix the small-file problem
-- MAGIC
-- MAGIC Remember `numFiles` from Step 4. Every change we have made wrote new files, so a
-- MAGIC busy table drifts towards thousands of small ones — and reading a thousand small
-- MAGIC files is far slower than reading a few large ones.
-- MAGIC
-- MAGIC `OPTIMIZE` compacts them. It changes no data and no results, only storage layout.
-- MAGIC `ZORDER BY` goes further, physically co-locating related rows so queries filtering
-- MAGIC on those columns can skip whole files.
-- MAGIC
-- MAGIC *(Our table is tiny so the gain is theoretical — but this is the same command you
-- MAGIC would run on a billion rows.)*

-- COMMAND ----------

OPTIMIZE orders ZORDER BY (region);

-- COMMAND ----------

-- Compare numFiles with Step 4.
DESCRIBE DETAIL orders;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 20 — Retention: how far back you can go
-- MAGIC
-- MAGIC | Property | Default | Controls |
-- MAGIC |---|---|---|
-- MAGIC | `delta.logRetentionDuration` | 30 days | How long the log keeps version entries |
-- MAGIC | `delta.deletedFileRetentionDuration` | 7 days | How long the data files are kept |
-- MAGIC
-- MAGIC **The effective limit is the smaller of the two — 7 days by default.** The log may
-- MAGIC still list version 5, but if its files are gone the query fails.

-- COMMAND ----------

ALTER TABLE orders SET TBLPROPERTIES (
  'delta.logRetentionDuration'         = 'interval 90 days',
  'delta.deletedFileRetentionDuration' = 'interval 30 days'
);

SHOW TBLPROPERTIES orders;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 21 — `VACUUM`: reclaim storage, at a price
-- MAGIC
-- MAGIC `VACUUM` deletes files no longer referenced and older than the retention period.
-- MAGIC
-- MAGIC > **State the trade-off plainly: `VACUUM` permanently destroys your ability to time
-- MAGIC > travel and to `RESTORE` past the retention window.** It is not reversible.
-- MAGIC > Shortening the window to save storage is exactly the decision that leaves you
-- MAGIC > unable to recover from a bad load. Decide the window before you need it.
-- MAGIC
-- MAGIC **Three things destroy rollback ability, and all three are done to save money:**
-- MAGIC `VACUUM` with short retention · shortening `deletedFileRetentionDuration` ·
-- MAGIC `VACUUM` on a **shallow clone's source**, which leaves the clone unreadable.
-- MAGIC
-- MAGIC `DRY RUN` lists what *would* be deleted without deleting anything. Always run it
-- MAGIC first. Nothing here is old enough to qualify — the expected result.

-- COMMAND ----------

VACUUM orders DRY RUN;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Step 22 — Blue/green swap
-- MAGIC
-- MAGIC **Use when** rebuilding a table people are actively querying, and a half-finished
-- MAGIC state must never be visible.
-- MAGIC
-- MAGIC 1. Build the new version **beside** the live table
-- MAGIC 2. **Check it** — counts, totals, spot checks
-- MAGIC 3. **Swap the names** — instant, metadata only
-- MAGIC 4. Keep the old table as the rollback
-- MAGIC
-- MAGIC **Why bother, when Delta writes are already atomic?** Because the *checking* step is
-- MAGIC the point. A transaction guarantees the write completed; it does not guarantee the
-- MAGIC result is correct. Blue/green lets you inspect before anyone sees it, and makes
-- MAGIC rollback a rename rather than a restore.

-- COMMAND ----------

-- 1. Build alongside.
CREATE OR REPLACE TABLE orders_new AS
SELECT order_id, customer, upper(region) AS region, product,
       quantity, unit_price, order_date, status, discount_pct
FROM orders;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ### 2. Verify before swapping — the whole value of the pattern
-- MAGIC If these disagree you stop here, and nobody downstream ever knew.

-- COMMAND ----------

SELECT 'live' AS which, count(*) AS rows, sum(quantity * unit_price) AS revenue FROM orders
UNION ALL
SELECT 'new',           count(*),          sum(quantity * unit_price)           FROM orders_new;

-- COMMAND ----------

-- 3. Swap. Instant, metadata only. orders_old is the rollback.
ALTER TABLE orders     RENAME TO orders_old;
ALTER TABLE orders_new RENAME TO orders;

SELECT order_id, customer, region, status FROM orders ORDER BY order_id;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC # Recap
-- MAGIC
-- MAGIC ## Part 1-2: creating and changing
-- MAGIC | Command | Why it matters |
-- MAGIC |---|---|
-- MAGIC | `CREATE TABLE` | Delta by default; identity columns, `NOT NULL`, Change Data Feed |
-- MAGIC | `INSERT` | All-or-nothing writes — never a half-loaded table |
-- MAGIC | `UPDATE` / `DELETE` | Row-level change; makes GDPR erasure practical |
-- MAGIC | `MERGE` | Apply updates *and* inserts atomically |
-- MAGIC
-- MAGIC ## Part 3: history
-- MAGIC | Command | Use it for |
-- MAGIC |---|---|
-- MAGIC | `DESCRIBE HISTORY` | Who changed what, when, how many rows |
-- MAGIC | `VERSION AS OF` / `@v1` | Exact, reproducible access to a known state |
-- MAGIC | Join two versions | See precisely what changed between two points |
-- MAGIC | `table_changes()` | Row-level before/after; feed downstream systems |
-- MAGIC
-- MAGIC ## Part 4: recovery
-- MAGIC | Strategy | Use when | Main risk |
-- MAGIC |---|---|---|
-- MAGIC | Full `RESTORE` | Whole table wrong, nothing good since | Discards later legitimate changes |
-- MAGIC | Surgical `MERGE` | Some rows wrong, good work must survive | Needs a key to match on |
-- MAGIC | `UNDROP TABLE` | Table was dropped | 7-day window; managed only |
-- MAGIC | Clone checkpoint | Before a risky change | Shallow clone breaks if source vacuumed |
-- MAGIC | Blue/green swap | Rebuild with zero bad visibility | Needs storage for two copies |
-- MAGIC
-- MAGIC ## Part 5-6: evolving and maintaining
-- MAGIC | Command | Why |
-- MAGIC |---|---|
-- MAGIC | `ALTER TABLE ADD COLUMN` | Evolve deliberately, without a rebuild |
-- MAGIC | `CHECK` constraint | Bad data refused at the table, for every writer |
-- MAGIC | `OPTIMIZE` / `ZORDER` | Fix small files; skip files on read |
-- MAGIC | Retention properties | Decide how far back you can go — before you need it |
-- MAGIC | `VACUUM` | Reclaim storage, at the cost of time travel |
-- MAGIC
-- MAGIC ## Three rules worth remembering
-- MAGIC 1. **Note the version number before any risky change.** Cheapest insurance there is.
-- MAGIC 2. **Match the fix to the damage.** Restoring a whole table to repair forty rows
-- MAGIC    destroys everyone else's work since.
-- MAGIC 3. **Rehearse on a clone.** A real incident is the wrong moment for your first
-- MAGIC    attempt at a command.
-- MAGIC
-- MAGIC ### The one-sentence takeaway
-- MAGIC **Delta gives files in cloud storage the guarantees of a database — transactions,
-- MAGIC row-level changes, a full history and several ways to undo — so the lakehouse is
-- MAGIC somewhere you can safely run the business, not just store its data.**

-- COMMAND ----------

-- Uncomment to remove everything this notebook created.
-- DROP CATALOG IF EXISTS demo_delta_e2e CASCADE;

SELECT 'Delta end-to-end demo complete' AS status;
